name: Backup
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang version
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            git clone https://github.com/xtls/xray-core xray-core > /dev/null
            cd xray-core/main
            GOOS=linux GOARCH=amd64 go build -o ../../xray
            cd ../../
            upx -9 xray
            shopt -s extglob
            rm -vrf !("xray")

            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null

            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "xray amd64 binary"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
            
